Custom editors for Swivel, Tumble
mjavaly/Prairie pull request #117
Opened 2017-02-02 16:42 UTC by mjavaly

Also renamed Swivel and Tumble, and changed their default prompts.

2017-02-02 19:07 UTC, grahamearley requested changes
Looking good. I made two minor change requests (removing "Click to" from your default prompts)

2017-02-02 19:07 UTC, grahamearley commented on Project/Assets/Prairie/Framework/Script/Interaction/Swivel.cs
> +			return "Click to Open/Close Door";
I think we're getting rid of "Click to" in our prompts. The other default prompts just have the action. Could you change this to "Open/Close door"?

2017-02-02 19:07 UTC, grahamearley commented on Project/Assets/Prairie/Framework/Script/Interaction/Tumble.cs
> +			return "Click to Pick Up Object";
Same here -- no "click to"

2017-02-03 00:55 UTC, grahamearley approved these changes
🛀 where's the like button???

2017-02-03 08:53 UTC, shoemakerc approved these changes
Great job!

2017-02-03 08:53 UTC, merged