made fields read only
mjavaly/Prairie pull request #120
Opened 2017-02-05 06:24 UTC by brennan724

I took the fields that we already have and made them read only.  They look exactly like they did before, but now read only (and thus you cannot add or remove fields either).  When you click on an uneditable object, then it flashes the object that you clicked on in the hierarchy (or the assets if you have not dragged it into the hierarchy).

For the lists particularly, it is possible to make it so that the plus and minus buttons are there.  However, it would mean more or less rewriting the original display functions with just a few minor tweaks, which I am willing to do.  It just means chunks of repeated code, which in general we want to avoid, but might make things look nicer.  So we might want to figure out if we want the plus and minus buttons or not.

I did not make read only fields of everything (because I didn't think we needed them), but I can do so if we want to.

I also found this other way of making fields read only, but I think us making our own GUIs conflicted with it (and I couldn't get it to work properly anyways).  We can attempt to use it (and tweak it) if you think that is a better idea, so that's why the link is below.
http://answers.unity3d.com/questions/489942/how-to-make-a-readonly-property-in-inspector.html

2017-02-05 20:00 UTC, grahamearley approved these changes
Slick solution

2017-02-06 00:33 UTC, cpimhoff requested changes
This is a slick solution indeed.

Super minor notes that should take less than 2 minutes to change (if we're in agreement about them)

2017-02-06 00:33 UTC, cpimhoff commented on Project/Assets/Editor/CustomInspectors/TwineNodeEditor.cs
> +		node.tags = PrairieGUI.drawPrimitiveListReadOnly ("Tags", node.tags);
I don't think there are many compelling reasons to include `tags` as part of the GUI. I can't imagine a situation in which a user would need to consult the tags array on a `TwineNode` after import.

2017-02-06 00:33 UTC, cpimhoff commented on Project/Assets/Editor/CustomInspectors/TwineNodeEditor.cs
> +		node.name = PrairieGUI.TextFieldReadOnly ("Name", node.name);
A standard `GUILayout.Label` would be cleaner than a disabled text box.

2017-02-06 19:02 UTC, brennan724 commented
@cpimhoff I made those changes to the name and to the tags (hid them).  Children and parents are still disabled boxes.  Is this all right?  At the moment, you can click on them and they will take you to what they are in the hierarchy (will flash them), but if they are labels instead, I don't think they will do that.  Also, I don't remember if we are actively displaying the content from the twine nodes.  Should these spaces be TextAreas instead of TextFields?

2017-02-07 01:25 UTC, brennan724 commented
![image](https://cloud.githubusercontent.com/assets/8431570/22673808/fe65fdd6-eca1-11e6-9496-e5474d230864.png)

2017-02-07 01:26 UTC, cpimhoff approved these changes

2017-02-07 01:26 UTC, merged