Matt/interactions
mjavaly/Prairie pull request #78
Opened 2017-01-19 20:44 UTC by mjavaly

some code cleanup, removed the string "Click To" in promptText, and overall improvements of SwivelInteraction and TumbleInteraction.

2017-01-19 21:07 UTC, shoemakerc approved these changes
Looks good!

2017-01-19 21:32 UTC, cpimhoff approved these changes

2017-01-19 21:36 UTC, cpimhoff requested changes
Interactions should not grab a reference to a Prompt object and chnage its contents. This would be overriding the user inputted prompt text at runtime, which nobody would expect.

Additionally, doing so voids our goal of having multiple interactions on an object *not* fight over control of the prompt field.

2017-01-20 21:50 UTC, Donahuec approved these changes
Looks good to me. @cpimhoff You should take a look and make sure the changes are what you wanted

2017-01-20 22:19 UTC, cpimhoff approved these changes

2017-01-20 22:19 UTC, merged