Prompt defaults when automatically added in editor
mjavaly/Prairie pull request #84
Opened 2017-01-20 23:00 UTC by cpimhoff

Fix for the concern raised in #82.

`Interactions` can now provide a default prompt value, which will be automatically inserted into the new prompt (when it is first added).

I provided such defaults for our existing `Interactions` in common use.

2017-01-20 23:04 UTC, grahamearley commented
I'm not sure about this as a full-on fix for the UI issue of noticing prompts. 

I don't think anyone would want their story to have interaction prompts say things like "Click to toggle something", so if the goal is to get people to notice that they should change the prompt, we might as well make the default prompt be "YOU SHOULD CHANGE THIS PROMPT."

Let's talk about it in our next meeting. Maybe there's some way we could call attention to the prompt when it's added.

2017-01-20 23:04 UTC, grahamearley requested changes
for discussion later

2017-01-20 23:06 UTC, brennan724 commented
Just making a note for myself as well so I don't forget, but what about including the field in the interaction itself, rather than in the prompt?  It would be a custom UI, but then people are more likely to do something about it when they are going through the interaction filling things out.

2017-01-20 23:09 UTC, cpimhoff commented
@grahamearley, I agree that "Toggle something" isn't something you'd want to keep, but the point is it is a default to be changed. It's just to give some guidance. Would "Toggle <SOMETHING>" be clearer in your eyes?

@brennan724 Moving to `Prompt` as a separate component was entirely to avoid having `Interaction` be in charge of prompt. `Prompt` applies to the whole object because all interactions on an object are activated wholesale. I think moving back to that approach would be a step backwards.

2017-01-20 23:10 UTC, brennan724 commented
Is there a way to leave the prompt as a separate component and just include the prompt field in the interaction?

2017-01-20 23:12 UTC, cpimhoff commented
@brennan724 I mean, sure, but `Prompt` would still show up (as empty) in the UI field, which I'd argue would be more confusing. The goal here is the message to the users. Attaching it to the `Interaction` implies that it is somehow linked to one *and only one* component on the object, which is not true.

2017-01-21 04:50 UTC, mjavaly commented
I agree with Graham that this should be discussed at our next meeting. This could very well be a creator's first foray into scene-building, and a default prompt could go a long way in pointing them in the right direction - whether that direction is to change the prompt or delete it altogether. In any case, I think it should go over fine with the user as long as we document it well.

2017-01-21 04:51 UTC, mjavaly approved these changes
I am personally in favor of this change, but we should talk about it first.

2017-01-23 01:39 UTC, grahamearley approved these changes
Alrighty!

2017-01-23 01:39 UTC, merged